# Generated by Django 3.2 on 2021-05-22 11:12

import Hospital.hospital_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20210521_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contacts',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='other_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(blank=True, default=Hospital.hospital_models.create_new_ref_number, editable=False, max_length=10, unique=True),
        ),
    ]
