# Generated by Django 3.2 on 2021-05-25 13:05

import Hospital.hospital_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20210522_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(blank=True, default=Hospital.hospital_models.Patient.generate_num, editable=False, max_length=10, unique=True),
        ),
    ]
