# Generated by Django 3.2 on 2021-05-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_diagnoses_complaints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnoses',
            new_name='Diagnosis',
        ),
    ]
