# Generated by Django 3.2 on 2021-05-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_rename_diagnoses_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(unique=True),
        ),
    ]
