# Generated by Django 3.2 on 2021-05-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_alter_batch_batch_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='type_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('complete', 'Complete')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateField(),
        ),
    ]
