# Generated by Django 3.2 on 2021-05-26 19:08

import DTS.stock_models
import DTS.transaction_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DTS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('actual_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, default=DTS.transaction_models.Transaction.generate_num, editable=False, max_length=10, unique=True)),
                ('transaction_type', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('quantity_measure', models.CharField(max_length=2)),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='tmda_verified',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='serial_number',
            field=models.CharField(blank=True, default=DTS.stock_models.Medicine.generate_num, editable=False, max_length=10, unique=True),
        ),
        migrations.RenameModel(
            old_name='UserType',
            new_name='Designation',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='transaction',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DTS.medicine'),
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DTS.designation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DTS.location'),
        ),
    ]
