# Generated by Django 3.2 on 2021-06-01 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0005_auto_20210601_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='DTS.transactiontype'),
        ),
    ]
