# Generated by Django 3.2 on 2021-06-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0008_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='quantity_of_measure',
            new_name='quantity_measure',
        ),
    ]
