# Generated by Django 3.2 on 2021-06-04 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0010_transaction_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_type',
        ),
        migrations.AddField(
            model_name='batch',
            name='medicine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DTS.medicinetype'),
        ),
        migrations.AlterField(
            model_name='local',
            name='area',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('institute_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DTS.institutetype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DTS.local')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='location_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='source', to='DTS.institute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='location_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='DTS.institute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DTS.institute'),
        ),
    ]
