# Generated by Django 3.2 on 2021-06-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0011_auto_20210604_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
