# Generated by Django 3.2 on 2021-06-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0012_alter_batch_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='on_route',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
