# Generated by Django 3.2 on 2021-06-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0014_alter_batch_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='unit_of_measure',
        ),
        migrations.AddField(
            model_name='batch',
            name='unit_of_measure',
            field=models.IntegerField(default=100),
        ),
    ]
