# Generated by Django 3.2 on 2021-06-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0015_auto_20210604_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='on_route',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='used',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
