# Generated by Django 3.2 on 2021-06-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0016_auto_20210604_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='concentration',
            field=models.CharField(default='20mg', max_length=15),
            preserve_default=False,
        ),
    ]
