# Generated by Django 3.2 on 2021-06-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0018_auto_20210604_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
