# Generated by Django 3.2 on 2021-06-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0021_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='TMDA_status',
        ),
    ]
