# Generated by Django 3.2 on 2021-06-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0022_remove_batch_tmda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='aprroval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='DTS.approval'),
            preserve_default=False,
        ),
    ]
